version: '3.7'

# Define services
services:
  backend-server:
    build:
      context: ./backend/demo-Web
      dockerfile: dockerfile
    ports:
      - "8888:8080" 
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/projetdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ubuntu
      SPRING_DATASOURCE_PASSWORD: ubuntu     
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

   # Frontend Service 
  front-app:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "9091:80" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - backend-server
    networks:
      - frontend  

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "33098:3306"
    restart: always
    environment:
      MYSQL_DATABASE: projetdb
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: ubuntu
      MYSQL_ROOT_PASSWORD: ubuntu
    volumes:
      - db-data:/var/lib/mysql
      - ./MySQL_Init_Script:/docker-entrypoint-initdb.d
    networks:
      - backend  
  
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: 
